samples: config/samples.tsv

# The file extension. Usually one of .fq.gz/.fastq.gz/.fq/.fastq
# Any additional 'tag' such as _R1_001 which trails the values provided
# in the samples file should be specified as the tag
ext: .fq.gz
tag: .r_1

# The root argument tells you where the genome will be located
# on the local system. All other arguments are required for
# downloading
ref:
  build: GRCh38
  release: 101
  root: /hpcfs/users/a1018048/refs
  seqtype: primary_assembly
  species: homo_sapiens

# Given we only have 75nt reads, don't group during fastqc
fastqc:
  params: "--nogroup --noextract"

# Settings for Adapter Removal
trimming:
  adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  maxns: 1
  minlength: 35
  minqual: 30
  extra: "--gzip --trimqualities"

# Settings for featureCounts
featureCounts:
  minQual: 1
  minOverlap: 35
  fracOverlap: 0.9
  strandedness: 0
  extra: "-M --fraction"

# Parameters for QC & Analysis.
# These must correspond to columns in the samples file
# and will be ignored if not. The 'group' value refers
# to the primary grouping of interest, whilst the 'batch'
# value refers to any secondary variables or confounders
analysis:
  group: treat
  batch: flowcell_id
